FROM python:3.12-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc build-essential curl ca-certificates bash \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN pip install --upgrade pip && \
    pip install uv uvicorn fastapi pytest

COPY testing/requirements.txt ./testing/requirements.txt
RUN pip install -r testing/requirements.txt

COPY movie_shop_backend/pyproject.toml .
COPY movie_shop_backend/uv.lock .
COPY movie_shop_backend/src ./src
COPY movie_shop_backend/app_state.json .
COPY testing ./testing  

RUN mkdir -p data reports && mv app_state.json data/

RUN mkdir -p /home/appuser/.cache/uv \
    && chown -R appuser:appuser /home/appuser/.cache

ENV UV_CACHE_DIR=/home/appuser/.cache/uv
ENV XDG_CACHE_HOME=/home/appuser/.cache
RUN chown -R appuser:appuser /app
USER appuser

ENV STATE_FILE=/app/data/app_state.json
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
